### ISSUE TITLE
separation between default payload, and custom payload in the viewer(macOS)

### ISSUE THREAD

**Issue by BenjiMandel** [TelemetryDeck/TelemetryViewer#112]
Currently, all the payload that is sent to the server is viewed in one chunk. (see image) if would be nice to have a separation between the default payload, the system info, and the custom payload I have sent to the server. 

![CleanShot of Telemetry Viewer on 2021-07-29 at 22 04 25](https://user-images.githubusercontent.com/44818620/127558530-16a895fa-6327-4fab-8cb2-15c9b10d97e0.png)

**Comment by winsmith** [comment]
This'll be in the next version!
