### ISSUE TITLE
Weblink entries in "Meta" section don't indicate app leave (but should)

### ISSUE THREAD

**Issue by Jeehut** [TelemetryDeck/TelemetryViewer#142]
These two entries in the Meta section of the app don't indicate that pressing them will leave the app, which they should for a better user experience. I find myself pressing them to see what lies behind them, just to see the browser open and have to swipe back to the app. I think it would be better to indicate that these buttons don't have any in-app screens (as of yet).

![IMG_2846](https://user-images.githubusercontent.com/6942160/186844226-f45ee61f-518a-43bb-83b7-4d55deedb8e0.jpeg)

I suggest we simply add this arrow SF Symbol icon:
![Screen Shot 2022-08-26 at 09 18 07](https://user-images.githubusercontent.com/6942160/186845178-83a275f2-1eea-417f-b807-496007502947.png)

I'd be up to implement this myself sometime within the next weeks, unless someone else is faster. I'm gonna leave a comment before starting to fix it, please do the same if you choose to fix yourself.

**Context Info**:
iPhone 12 Pro Max, iOS 16.0 beta 6, App Version 1.0.0 (680)

**Comment by winsmith** [comment]
Good idea, thank you very much!

I'll add that there is a chance we'll have to remove those two buttons from iOS to pass App Store Review.

**Comment by Drag0ndust** [comment]
I added the requested icons
