### ISSUE TITLE
Starting the app in portrait on iPad without being signed in, login options are not shown

### ISSUE THREAD

**Issue by marcpalmer** [TelemetryDeck/TelemetryViewer#148]
This only occurs if you are not signed in at all when the app starts.

The sign-in options are all in the sidebar which of course does not show by default. I think the solution to this is to not have the sign in content in the sidebar, it should be the main content that is always shown, as if you are not signed in there's nothing else you can do.

![image](https://user-images.githubusercontent.com/40849/216119256-9a8c4325-cc46-442d-84c8-2249296aca42.png)

**Comment by JayFiDev** [comment]
I will send a pull request soon for this! I propose to switch the it from the default behavior to the stack behavior of the NavigationView. It has the same defaults then like on the iPhone.
