### ISSUE TITLE
Signing in with email the first time on iPad, the sign in button below the fields is often not visible

### ISSUE THREAD

**Issue by marcpalmer** [TelemetryDeck/TelemetryViewer#149]
The illustration image is far too large and this pushes the button below the default window size / iPad screen size.

![Screenshot 2023-02-01 at 17 20 38](https://user-images.githubusercontent.com/40849/216119792-061d51eb-88b1-49ac-a093-838f2451bcf6.jpg)

**Comment by marcpalmer** [comment]
I have a simple workaround for this to set a max height on the image that I will make a PR for.

**Comment by winsmith** [comment]
Wow Marc you're on fire! 🤩
