### ISSUE TITLE
Can't login from Telemetry Viewer

### ISSUE THREAD

**Issue by winsmith** [TelemetryDeck/TelemetryViewer#168]

**Comment by 3DTOPO** [comment]
I can't login either. My login works on the dashboard.telemetrydeck.com using build (709)

<img width="937" alt="Screenshot 2024-04-02 at 7 29 38 PM" src="https://github.com/TelemetryDeck/TelemetryViewer/assets/352383/0d5dba10-94ca-4631-93d7-65b3a980e852">
